### ISSUE TITLE
Impossible to configure several memcached blocks

### ISSUE THREAD

**Issue by broferek** [grafana/mimir#1708]
#### Describe the bug

I want to use Memcached wherever possible (chunk cache, frontend results cache). However, when I try to use more than one configuration block of memcached, I get the following error on startup :
```
panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "thanos_memcached_dns_provider_results", help: "The number of resolved endpoints for each configured address", constLabels: {name="frontend-cache"}, variableLabels: [addr]} has different label names or a different help string

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc0006b6f60, {0xc0004954f0, 0x1, 0x40d3e7})
        /__w/mimir/mimir/vendor/github.com/prometheus/client_golang/prometheus/wrap.go:104 +0x151
github.com/thanos-io/thanos/pkg/extprom.NewTxGaugeVec({0x20fc680, 0xc0006b6f60}, {{0x0, 0x0}, {0x0, 0x0}, {0x1c57cbb, 0x14}, {0x1cc1bd2, 0x3c}, ...}, ...)
        /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/extprom/tx_gauge.go:42 +0x212
github.com/thanos-io/thanos/pkg/discovery/dns.NewProvider({0x20dec60, 0xc000b42230}, {0x20fc680, 0xc0006b6f60}, {0x1c4109b, 0x7fe5a63e95c0})
        /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go:64 +0x187
github.com/thanos-io/thanos/pkg/cacheutil.newMemcachedClient({0x20dec60, 0xc000b42230}, {0x20f4c00, 0xc000c60800}, 0xc0006b6ea0, {{0xc000495410, 0x1, 0x1}, 0xbebc200, 0x64, ...}, ...)
        /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go:256 +0x1ca
github.com/thanos-io/thanos/pkg/cacheutil.NewMemcachedClientWithConfig({0x20dec60, 0xc000b42230}, {0x1c4b648, 0xe}, {{0xc000495410, 0x1, 0x1}, 0xbebc200, 0x64, 0x32, ...}, ...)
        /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go:235 +0x295
github.com/grafana/mimir/pkg/cache.CreateClient({0x1c4b648, 0xe}, {{0xc000040440, 0x9}, {{0xc0002bbad0, 0x30}, 0xbebc200, 0x64, 0x32, 0x61a8, ...}}, ...)
        /__w/mimir/mimir/pkg/cache/cache.go:52 +0x188
github.com/grafana/mimir/pkg/frontend/querymiddleware.newResultsCache({{{0xc000040440, 0x9}, {{0xc0002bbad0, 0x30}, 0xbebc200, 0x64, 0x32, 0x61a8, 0x64, 0x64, ...}}, ...}, ...)
        /__w/mimir/mimir/pkg/frontend/querymiddleware/results_cache.go:82 +0x92
github.com/grafana/mimir/pkg/frontend/querymiddleware.newQueryTripperware({0x4e94914f0000, 0x1, {{{0xc000040440, 0x9}, {{...}, 0xbebc200, 0x64, 0x32, 0x61a8, 0x64, ...}}, ...}, ...}, ...)
        /__w/mimir/mimir/pkg/frontend/querymiddleware/roundtrip.go:177 +0x365
github.com/grafana/mimir/pkg/frontend/querymiddleware.NewTripperware({0x4e94914f0000, 0x1, {{{0xc000040440, 0x9}, {{...}, 0xbebc200, 0x64, 0x32, 0x61a8, 0x64, ...}}, ...}, ...}, ...)
        /__w/mimir/mimir/pkg/frontend/querymiddleware/roundtrip.go:138 +0xfe
github.com/grafana/mimir/pkg/mimir.(*Mimir).initQueryFrontendTripperware(0xc000a19000)
        /__w/mimir/mimir/pkg/mimir/modules.go:481 +0x1e5
github.com/grafana/dskit/modules.(*Manager).initModule(0xc000116480, {0x1c3a18b, 0x1c72b3a}, 0x1e, 0x0)
        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:120 +0x224
github.com/grafana/dskit/modules.(*Manager).InitModuleServices(0x1984080, {0xc000494de0, 0x1, 0x3})
        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:92 +0x10c
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run(0xc000a19000)
        /__w/mimir/mimir/pkg/mimir/mimir.go:426 +0x21c
main.main()
        /__w/mimir/mimir/cmd/mimir/main.go:195 +0xcd3
```

I saw it was recommended to use different Memcached instances for each cache however even in this case, the problem occurs.

#### To Reproduce
1. Configure Mimir
```
blocks_storage:
    backend: "s3"
    bucket_store:
        chunks_cache:
            backend: "memcached"
            memcached:
                addresses: "<instance>:11211"
```
and
```frontend:
    cache_results: true
    results_cache:
        backend: "memcached"
        memcached:
            addresses: "<instance>:11212" 
```
2. Start Mimir (2.0.0)
3. Fail to start on the above error

#### Expected behavior

A working Mimir instance using Memcached instances.

#### Environment

- Infrastructure: bare-metal
- Deployment tool: Podman

**Comment by pracucci** [comment]
Thanks for your report! It was reported here https://github.com/grafana/mimir/issues/1698 and fixed yesterday (fix will be included in the next release). The bug happens with running Mimir in single binary mode **and** query-frontend results cache is configured.

> fix will be included in the next release

To get it immediately, are you willing to build Mimir from `main`? You can build Mimir Docker image running this command:
```
make ./cmd/mimir/.uptodate
```

**Comment by pracucci** [comment]
Duplicate of https://github.com/grafana/mimir/issues/1698

**Comment by broferek** [comment]
Sorry, I hadn't seen the other issue even tough I had looked up if someone had already reported it.

I'll wait for the next release then and live without frontend results cache until then.

Closing the issue

**Comment by pracucci** [comment]
> I'll wait for the next release then and live without frontend results cache until then.

Alternatively, you may consider running the query-frontend as separate component (run it with the same Mimir config).
