### ISSUE TITLE
store-gateway 2.4.0 panic: snappy: decoded block is too large

### ISSUE THREAD

**Issue by agardiman** [grafana/mimir#3700]
#### Describe the bug
The store-gateways were running without issues for about 2 weeks. Suddenly, around the same few minutes, almost all of them panicked with the following erorr
```
➜  ~ kubectl logs --timestamps=true -p --tail 20 store-gateway-99
2022-12-07T17:24:36.368530205Z level=info ts=2022-12-07T17:24:36.36844047Z caller=gateway.go:294 msg="successfully synchronized TSDB blocks for all users" reason=periodic
2022-12-07T17:37:31.142131143Z level=info ts=2022-12-07T17:37:31.141993381Z caller=gateway.go:288 msg="synchronizing TSDB blocks for all users" reason=periodic
2022-12-07T17:37:31.231003166Z level=info ts=2022-12-07T17:37:31.230863755Z caller=gateway.go:294 msg="successfully synchronized TSDB blocks for all users" reason=periodic
2022-12-07T17:47:14.230811410Z panic: snappy: decoded block is too large
2022-12-07T17:47:14.230840345Z
2022-12-07T17:47:14.230844443Z goroutine 7303110 [running]:
2022-12-07T17:47:14.230847767Z github.com/golang/snappy.Encode({0x0?, 0x1df6a60?, 0xc002df6040?}, {0xc32e7fc000?, 0x1df6a60?, 0xc002df6040?})
2022-12-07T17:47:14.230851367Z 	/__w/mimir/mimir/vendor/github.com/golang/snappy/encode.go:22 +0x2d1
2022-12-07T17:47:14.230855078Z github.com/grafana/mimir/pkg/storegateway.encodeSnappyGob({0x1df6a60, 0xc002df6040})
2022-12-07T17:47:14.230858287Z 	/__w/mimir/mimir/pkg/storegateway/snappy_gob_codec.go:23 +0x24f
2022-12-07T17:47:14.230865883Z github.com/grafana/mimir/pkg/storegateway.storeCachedSeries({0x2633030, 0xc096fe9440}, {0x2649a78, 0xc000db2340}, {0xc00066a9b8, 0x7}, {0x1, 0x84, 0xeb, 0x27, ...}, ...)
2022-12-07T17:47:14.230869450Z 	/__w/mimir/mimir/pkg/storegateway/bucket.go:760 +0x1ab
2022-12-07T17:47:14.230900236Z github.com/grafana/mimir/pkg/storegateway.blockSeries({0x2633030?, 0xc096fe9350?}, 0xc096fe93b0, 0x0, {0xc0a7bce850, 0x1, 0x1}, 0x0, 0x0, {0x26193c0, ...}, ...)
2022-12-07T17:47:14.230908589Z 	/__w/mimir/mimir/pkg/storegateway/bucket.go:707 +0xaa5
2022-12-07T17:47:14.230911827Z github.com/grafana/mimir/pkg/storegateway.(*BucketStore).Series.func2()
2022-12-07T17:47:14.230915200Z 	/__w/mimir/mimir/pkg/storegateway/bucket.go:940 +0x1e5
2022-12-07T17:47:14.230934359Z golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-12-07T17:47:14.230937860Z 	/__w/mimir/mimir/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x64
2022-12-07T17:47:14.230941420Z created by golang.org/x/sync/errgroup.(*Group).Go
2022-12-07T17:47:14.230943737Z 	/__w/mimir/mimir/vendor/golang.org/x/sync/errgroup/errgroup.go:72 +0xa5
```

#### To Reproduce
Not sure

#### Expected behavior
To not crash

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: jsonnet
- Mimir: v2.4.0

**Comment by chencs** [comment]
We have found that the querier will also panic if a remote read request generates a >4GB response ([code](https://github.com/grafana/mimir/blob/b69b4f481f2e2cd694ea5e8959b21d12ce8e38fb/pkg/util/http.go#L307)). I am working on fixing this issue in both places.
