### ISSUE TITLE
panic: runtime error: index out of range in the compactor with native histograms

### ISSUE THREAD

**Issue by aptomaKetil** [grafana/mimir#4702]
#### Describe the bug
The compactor panics after a few hours of ingesting native histograms coming from the OTLP Collector.

#### To Reproduce

1. Start Mimir (r232-ff833f1)
2. Enable the [spanmetrics connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) in OTLP Connector, configure it to create exponential histograms, and send these to Mimir via the `otlphttp` exporter.

#### Expected behavior

Histograms are ingested without crashing the compactor.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

Nearly every batch of histograms caused warnings in the distributor of type `cannot convert exponential to native histogram. Scale must be <= 8 and >= -4, was X;`. It's difficult to know exactly what proportion of the data was dropped due to this limitation, the histogram data I had to work with in Grafana seemed to match our other metrics just fine.

I haven't been able to trigger this panic via other metric sources, but the volume of histograms coming out of the spanmetrics connector in the OTLP Collector is several orders of magnitude larger than my other sources, so that might just be a numbers game.

Compactor logs:

```
ts=2023-04-05T15:08:01.619168741Z caller=bucket_compactor.go:798 level=info component=compactor user=anonymous msg="start of GC"
ts=2023-04-05T15:08:01.619779848Z caller=bucket_compactor.go:842 level=info component=compactor user=anonymous msg="start of compactions"
ts=2023-04-05T15:08:01.61993208Z caller=bucket_compactor.go:301 level=info component=compactor user=anonymous groupKey=0@17241709254077376921-merge--1680696000000-1680703200000 minTime="2023-04-05 12:00:00 +0000 UTC" maxTime="2023-04-05 14:00:00 +0000 UTC" msg="compaction available and planned; downloading blocks" blocks=7 plan="[01GX8YZ2JA03DBDN0E154SCH4G (min time: 1680696000000, max time: 1680703200000) 01GX8XCADSBCJXXWA4XWGEM8NZ (min time: 1680696000000, max time: 1680703200000) 01GX8YYB5MHJEJ5JP1ZDGEBDG4 (min time: 1680696000000, max time: 1680703200000) 01GX8YYRA59FF5VQ22G6V60DQ6 (min time: 1680696000000, max time: 1680703200000) 01GX8YYN6VF8D8XSG6YHDHZH6X (min time: 1680696000000, max time: 1680703200000) 01GX8YY265BVH54WY1YXCD15XH (min time: 1680696000000, max time: 1680703200000) 01GX8YY9KKASYTYMGCSXX93NM7 (min time: 1680696000024, max time: 1680703200000)]"
ts=2023-04-05T15:08:03.596852178Z caller=bucket_compactor.go:349 level=info component=compactor user=anonymous groupKey=0@17241709254077376921-merge--1680696000000-1680703200000 minTime="2023-04-05 12:00:00 +0000 UTC" maxTime="2023-04-05 14:00:00 +0000 UTC" msg="downloaded and verified blocks; compacting blocks" blocks=7 plan="[/data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YZ2JA03DBDN0E154SCH4G /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8XCADSBCJXXWA4XWGEM8NZ /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YYB5MHJEJ5JP1ZDGEBDG4 /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YYRA59FF5VQ22G6V60DQ6 /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YYN6VF8D8XSG6YHDHZH6X /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YY265BVH54WY1YXCD15XH /data/compact/0@17241709254077376921-merge--1680696000000-1680703200000/01GX8YY9KKASYTYMGCSXX93NM7]" duration=1.976871967s duration_ms=1976
ts=2023-04-05T15:08:03.61115916Z caller=compact.go:980 level=info component=compactor msg="Found overlapping blocks during compaction"
ts=2023-04-05T15:08:08.972325963Z caller=bucket_compactor.go:274 level=info component=compactor user=anonymous groupKey=0@17241709254077376921-merge--1680696000000-1680703200000 minTime="2023-04-05 12:00:00 +0000 UTC" maxTime="2023-04-05 14:00:00 +0000 UTC" msg="compaction job succeeded" duration=7.352507853s duration_ms=7352
panic: runtime error: index out of range [3] with length 3

goroutine 1519 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).AppendHistogram(0x400471fa40, 0x187516641d7, 0x0?)
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:515 +0x58c
github.com/prometheus/prometheus/storage.(*seriesToChunkEncoder).Iterator(0x400481a480?, {0x0?, 0x0?})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/storage/series.go:335 +0x384
github.com/prometheus/prometheus/storage.(*compactChunkIterator).Next(0x40048357a0)
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/storage/merge.go:748 +0x544
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).populateBlock(0x4000cab000, {0x40003d0600, 0x7, 0x79?}, 0x1875149be00, 0x18751b79b00, {0x4001503040, 0x1, 0x1})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/compact.go:1089 +0x136c
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0x4000cab000, {0x4001069860, 0x47}, {0x4001503040?, 0x1, 0x1}, {0x40003d0600, 0x7, 0x8})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/compact.go:817 +0x720
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).compact(0x4000cab000, {0x4001069860, 0x47}, {0x40001f2000, 0x7, 0x7}, {0x0, 0x0, 0x0}, 0x1)
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/compact.go:490 +0x5c0
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Compact(0xa?, {0x4001069860?, 0x1?}, {0x40001f2000?, 0x4000c49a78?, 0x113770?}, {0x0?, 0x77968?, 0x0?})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/compact.go:437 +0x30
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).runCompactionJob(0x4000c38780, {0x2440750, 0x4000222ff0}, 0x4000132580)
	/__w/mimir/mimir/pkg/compactor/bucket_compactor.go:357 +0xbc4
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact.func2()
	/__w/mimir/mimir/pkg/compactor/bucket_compactor.go:744 +0x234
created by github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact
	/__w/mimir/mimir/pkg/compactor/bucket_compactor.go:728 +0x8b4
ts=2023-04-05T15:08:42.957235652Z caller=main.go:213 level=info msg="Starting application" version="(version=2.7.1, branch=r232, revision=ff833f1)"
```

The panic is always off by one, i.e. it's always `index out of range [N] with length N`. The value of `N` varies, but seems to be consistent for the same set of blocks.

I resolved the issue by disabling the spanmetrics, and used the `markblocks` tool to disable compaction for the relevant blocks.

**Comment by krajorama** [comment]
I think I reproduced this accidentally.
Checking to see if related to https://github.com/prometheus/prometheus/pull/12185

```
ts=2023-04-14T08:14:15.544357287Z caller=bucket_compactor.go:274 level=info component=compactor user=13611 groupKey=0@17241709254077376921-merge--1679925600000-1679932800000 minTime="2023-03-27 14:00:00.006 +0000 UTC" maxTime="2023-03-27 16:00:00 +0000 UTC" msg="compaction job succeeded" duration=603.556248ms duration_ms=603
panic: runtime error: index out of range [37] with length 37

goroutine 3206 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).AppendHistogram(0xc001091b30, 0x18723632642, 0x0?)
	/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:515 +0x685
github.com/prometheus/prometheus/storage.(*seriesToChunkEncoder).Iterator(0xc000ff5580?, {0x0?, 0x0?})
	/backend-enterprise/vendor/github.com/prometheus/prometheus/storage/series.go:335 +0x455
github.com/prometheus/prometheus/storage.(*compactChunkIterator).Next(0xc0012c0f30)
	/backend-enterprise/vendor/github.com/prometheus/prometheus/storage/merge.go:748 +0x6be
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).populateBlock(0xc001196d80, {0xc001420800, 0x15, 0x79?}, 0x187235e5f06, 0x18723cc3c00, {0xc0019c5d60, 0x1, 0x1})
	/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/compact.go:1089 +0x19bf
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc001196d80, {0xc00014aff0, 0x47}, {0xc0019c5d60?, 0x1, 0x1}, {0xc001420800, 0x15, 0x20})
	/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/compact.go:817 +0x973
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).compact(0xc001196d80, {0xc00014aff0, 0x47}, {0xc0010d5ce0, 0x15, 0x15}, {0x0, 0x0, 0x0}, 0x1)
	/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/compact.go:490 +0x7bc
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Compact(0xa?, {0xc00014aff0?, 0x1?}, {0xc0010d5ce0?, 0xef?, 0x4a99600?}, {0x0?, 0x0?, 0x102ceabc0?})
	/backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/compact.go:437 +0x45
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).runCompactionJob(0xc001664460, {0x34afda8, 0xc0016eae10}, 0xc000a85580)
	/backend-enterprise/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:357 +0xee6
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact.func2()
	/backend-enterprise/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:744 +0x313
created by github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact
	/backend-enterprise/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:728 +0xb2a
```

**Comment by krajorama** [comment]
I think it's the same issue as https://github.com/prometheus/prometheus/pull/12185 . I've found my two offending blocks and loaded them in a unit test and turned on debugging. 
Seems like we're trying to append a histogram with 38 buckets to a chunk where the histogram that we calculate delta with has 37 buckets.

**Comment by krajorama** [comment]
When I applied the fix proposed for https://github.com/prometheus/prometheus/pull/12185, the compaction does not fail anymore.
