### ISSUE TITLE
ingester: panic appending exemplars

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#5125]
@Leegin-darknight reported panics in ingesters on r239 ([slack thread](https://grafana.slack.com/archives/C039863E8P7/p1685442264059329)). During the panics the out-of-order window was 5 minutes. Switching to 3 hours and cleared the panics.

The address of 0x20 suggests that the series returned by `getByID` is nil 

https://github.com/grafana/mimir/blob/23e30d0a63d319fa19d33e3b796512e3179bc5ac/vendor/github.com/prometheus/prometheus/tsdb/head_append.go#L854-L856

```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11d87c5]

goroutine 590268 [running]:
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc6114a5b80)
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_append.go:856 +0x285
github.com/prometheus/prometheus/tsdb.dbAppender.Commit({{0x2b85b98?, 0xc6114a5b80?}, 0xc00149ed20?})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/db.go:1067 +0x35
github.com/grafana/mimir/pkg/ingester.(*Ingester).PushWithCleanup(0xc001085000, {0x2b79a60, 0xc612811ef0}, 0xc611480750)
	/__w/mimir/mimir/pkg/ingester/ingester.go:775 +0x102a
github.com/grafana/mimir/pkg/ingester.(*Ingester).Push(0x40bbe5?, {0x2b79a60, 0xc612811ef0}, 0xc5d4d529c0)
	/__w/mimir/mimir/pkg/ingester/ingester.go:2573 +0x1db
github.com/grafana/mimir/pkg/ingester.(*ActivityTrackerWrapper).Push(0x7f8ff97ee998?, {0x2b79a60?, 0xc612811ef0?}, 0x23c5c40?)
	/__w/mimir/mimir/pkg/ingester/ingester_activity.go:36 +0x26
github.com/grafana/mimir/pkg/ingester/client._Ingester_Push_Handler.func1({0x2b79a60, 0xc612811ef0}, {0x2424f40?, 0xc5d4d529c0})
	/__w/mimir/mimir/pkg/ingester/client/ingester.pb.go:3722 +0x78
github.com/grafana/mimir/pkg/mimir.ThanosTracerUnaryInterceptor({0x2b79a60?, 0xc612811ec0?}, {0x2424f40, 0xc5d4d529c0}, 0x2b79a60?, 0xc588be2ea0)
	/__w/mimir/mimir/pkg/mimir/tracing.go:25 +0x7a
google.golang.org/grpc.getChainUnaryHandler.func1({0x2b79a60, 0xc612811ec0}, {0x2424f40, 0xc5d4d529c0})
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1163 +0xb9
github.com/weaveworks/common/middleware.ServerUserHeaderInterceptor({0x2b79a60?, 0xc612811e60?}, {0x2424f40, 0xc5d4d529c0}, 0x285119aa8a3d5398?, 0xc5d4d52c40)
	/__w/mimir/mimir/vendor/github.com/weaveworks/common/middleware/grpc_auth.go:38 +0x65
github.com/grafana/mimir/pkg/util/noauth.SetupAuthMiddleware.func1({0x2b79a60, 0xc612811e60}, {0x2424f40, 0xc5d4d529c0}, 0xc487118d20, 0xc5d4d52c40)
	/__w/mimir/mimir/pkg/util/noauth/no_auth.go:32 +0xa7
google.golang.org/grpc.getChainUnaryHandler.func1({0x2b79a60, 0xc612811e60}, {0x2424f40, 0xc5d4d529c0})
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1163 +0xb9
github.com/weaveworks/common/middleware.UnaryServerInstrumentInterceptor.func1({0x2b79a60, 0xc612811e60}, {0x2424f40, 0xc5d4d529c0}, 0xc487118d20, 0xc5d4d52c00)
	/__w/mimir/mimir/vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go:35 +0xa2
google.golang.org/grpc.getChainUnaryHandler.func1({0x2b79a60, 0xc612811e60}, {0x2424f40, 0xc5d4d529c0})
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1163 +0xb9
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1({0x2b79a60, 0xc612811dd0}, {0x2424f40, 0xc5d4d529c0}, 0xc487118d20, 0xc5d4d52ac0)
	/__w/mimir/mimir/vendor/github.com/opentracing-contrib/go-grpc/server.go:57 +0x3f4
google.golang.org/grpc.getChainUnaryHandler.func1({0x2b79a60, 0xc612811dd0}, {0x2424f40, 0xc5d4d529c0})
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1163 +0xb9
github.com/weaveworks/common/middleware.GRPCServerLog.UnaryServerInterceptor({{0x2b90260?, 0xc000418170?}, 0x40?, 0xa?}, {0x2b79a60, 0xc612811dd0}, {0x2424f40, 0xc5d4d529c0}, 0xc487118d20, 0xc5d4d52a80)
	/__w/mimir/mimir/vendor/github.com/weaveworks/common/middleware/grpc_logging.go:30 +0xbb
google.golang.org/grpc.chainUnaryInterceptors.func1({0x2b79a60, 0xc612811dd0}, {0x2424f40, 0xc5d4d529c0}, 0xc60b2b0a50?, 0x2130000?)
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1154 +0x8f
github.com/grafana/mimir/pkg/ingester/client._Ingester_Push_Handler({0x23da9a0?, 0xc001095510}, {0x2b79a60, 0xc612811dd0}, 0xc611aba230, 0xc00056cec0)
	/__w/mimir/mimir/pkg/ingester/client/ingester.pb.go:3724 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f38000, {0x2b8f1c0, 0xc0ed5fa000}, 0xc60dd05b00, 0xc0010be3f0, 0x3d27a20, 0x0)
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc000f38000, {0x2b8f1c0, 0xc0ed5fa000}, 0xc60dd05b00, 0x0)
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/__w/mimir/mimir/vendor/google.golang.org/grpc/server.go:963 +0x28a

ts=2023-05-31T13:07:35.825113095Z caller=main.go:216 level=info msg="Starting application" version="(version=2.8.0, branch=r239, revision=071bdf6)"
```

**Comment by dimitarvdimitrov** [comment]
closing as old
