### ISSUE TITLE
Flaky test in github.com/grafana/mimir/pkg/ingester

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#5351]
```
panic: expected newly cut file to have sequence:offset 1:8, got 2:8

goroutine 9968 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x21f1ec0?, 0xc0020f4078?})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1518 +0x76
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).processJob(0xc000885b80, {0x1, 0x1, 0x1b77400, 0x1b77400, {0x220d5a8, 0xc00212f0a0}, 0x100000008, 0x0, 0x1e26478})
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:139 +0x8c
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start.func1()
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:127 +0xb8
created by github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start
	/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:118 +0x6d
FAIL	github.com/grafana/mimir/pkg/ingester	8.835s
```

From https://github.com/grafana/mimir/actions/runs/5376279053/jobs/9753226445#step:8:37.

**Comment by dimitarvdimitrov** [comment]
the test run is deleted, so it's hard to find which test that is. Should we close this issue and reopen once we know the test which caused it @pstibrany ?

**Comment by pstibrany** [comment]
Oh 🤦  I did not include enough details in this issue. I agree with your suggestion, closing.
