### ISSUE TITLE
Panic in query-frontend roundtripper when frontend.downstream_url is set

### ISSUE THREAD

**Issue by kjelljoakim** [grafana/mimir#7436]
#### Describe the bug

Setting `frontend.downstream_url` in 2.11.0 causes a panic in roundtripper on requests to query-frontend. The issue does not happen in 2.10.5 and seems to have been introduced in https://github.com/grafana/mimir/pull/6621.  More specifically [here](https://github.com/grafana/mimir/blob/c8939ea55f0818337e3428924f25dafc6ea256d1/pkg/mimir/modules.go#L696-L715).

Both `frontendv1` and `frontendv2` are returned as nil from `InitFrontend(...)` when downstream url is set leading to `frontendSvc` also being nil and `querymiddleware.NewFrontendRunningRoundTripper(...)` creating a roundtripper with a nil service.

Chaos then ensues [here](https://github.com/grafana/mimir/blob/33ef390e09fb988c39691fe1069c489fcb2747a2/pkg/frontend/querymiddleware/running.go#L36-L46) as `service` is nil in `awaitQueryFrontendServiceRunning(...)`

#### To Reproduce

1. Start Mimir 2.11.0 using config below

```yaml
frontend:
  downstream_url: http://localhost:3030
target: query-frontend

```

2. Run query:  `curl --location 'http://localhost:8080/prometheus/api/v1/query?query=test' \
--header 'X-Scope-OrgID: anonymous'`

#### Expected behavior

The query frontend to propagate query to `downstream_url`

#### Environment

Issue can reproduced on laptop with config above

#### Additional Context

Stack trace:

```
2024/02/21 17:42:02 http: panic serving [::1]:49542: runtime error: invalid memory address or nil pointer dereference
goroutine 211 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb0
panic({0x1044eaf20?, 0x105b8a800?})
        /usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:155 +0x17c
panic({0x1044eaf20?, 0x105b8a800?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/grafana/mimir/pkg/frontend/querymiddleware.awaitQueryFrontendServiceRunning({0x10490dc20, 0x14001bba660}, {0x0, 0x0}, 0x0, {0x1048eeff8, 0x14000552108})
        /Users/joakimkarlsson/IdeaProjects/mimir/pkg/frontend/querymiddleware/running.go:46 +0x4c
github.com/grafana/mimir/pkg/frontend/querymiddleware.(*frontendRunningRoundTripper).RoundTrip(0x1400157f9c0, 0x14001cac500)
        /Users/joakimkarlsson/IdeaProjects/mimir/pkg/frontend/querymiddleware/running.go:37 +0x64
github.com/grafana/mimir/pkg/frontend/transport.(*Handler).ServeHTTP(0x14000554fd0, {0x1049072c0?, 0x140000ac700}, 0x14001cac400)
        /Users/joakimkarlsson/IdeaProjects/mimir/pkg/frontend/transport/handler.go:193 +0x4e8
github.com/grafana/dskit/middleware.glob..func2.1({0x1049072c0, 0x140000ac700}, 0x14001cac300)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/grafana/dskit/middleware/http_auth.go:21 +0x100
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1049072c0?, 0x140000ac700?}, 0x4?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/grafana/mimir/pkg/util/gziphandler.GzipHandlerWithOpts.func1.1({0x104907950, 0x1400170a5c0}, 0x10488a8a0?)
        /Users/joakimkarlsson/IdeaProjects/mimir/pkg/util/gziphandler/gzip.go:357 +0x200
net/http.HandlerFunc.ServeHTTP(0x14001cac200?, {0x104907950?, 0x1400170a5c0?}, 0x14000aa4360?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/grafana/dskit/middleware.HTTPGRPCTracer.Wrap-fm.HTTPGRPCTracer.Wrap.func1({0x104907950, 0x1400170a5c0}, 0x14001cac200)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/grafana/dskit/middleware/http_tracing.go:131 +0x5f4
net/http.HandlerFunc.ServeHTTP(0x14001cac100?, {0x104907950?, 0x1400170a5c0?}, 0x1025776a0?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x1400018e600, {0x104907950, 0x1400170a5c0}, 0x14001cac000)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/gorilla/mux/mux.go:212 +0x194
github.com/grafana/dskit/middleware.(*Instrument).Wrap.Instrument.Wrap.func1.2({0x104907950?, 0x1400170a5c0?})
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/grafana/dskit/middleware/instrument.go:74 +0x40
github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics(0x1400054c420, {0x10d4a0198, 0x14001700120}, 0x140006d7798)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/felixge/httpsnoop/capture_metrics.go:84 +0x184
github.com/felixge/httpsnoop.CaptureMetricsFn({0x10d4a0198, 0x14001700120}, 0x14000964318?)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/felixge/httpsnoop/capture_metrics.go:39 +0x50
github.com/grafana/dskit/middleware.(*Instrument).Wrap.Instrument.Wrap.func1({0x10d4a0198, 0x14001700120}, 0x14001cac000)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/grafana/dskit/middleware/instrument.go:73 +0x254
net/http.HandlerFunc.ServeHTTP(0x104905df0?, {0x10d4a0198?, 0x14001700120?}, 0x14001bba240?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/grafana/dskit/middleware.(*Log).Wrap.Log.Wrap.func1({0x104905df0, 0x14001700060}, 0x14001cac000)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/grafana/dskit/middleware/logging.go:88 +0x200
net/http.HandlerFunc.ServeHTTP(0xf8?, {0x104905df0?, 0x14001700060?}, 0x1029da11c?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5({0x104902e60?, 0x140001a22a0}, 0x140001ae800)
        /Users/joakimkarlsson/IdeaProjects/mimir/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:159 +0x3e8
net/http.HandlerFunc.ServeHTTP(0x105bfb160?, {0x104902e60?, 0x140001a22a0?}, 0x140016b0b40?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
net/http.serverHandler.ServeHTTP({0x140016cc0c0?}, {0x104902e60?, 0x140001a22a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x14000984090, {0x10490dc20, 0x140015dd950})
        /usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 194
        /usr/local/go/src/net/http/server.go:3086 +0x4cc

```

**Comment by dimitarvdimitrov** [comment]
thanks for reporting it. You look already familiar with the issue, do you think you can open a PR with a fix?

**Comment by kjelljoakim** [comment]
> thanks for reporting it. You look already familiar with the issue, do you think you can open a PR with a fix?

Yes I can look into it
