### ISSUE TITLE
bug: distributor nil pointer

### ISSUE THREAD

**Issue by shichanglin5** [grafana/mimir#7759]
## log
```log
panic: runtime error: index out of range [0] with length 0

goroutine 3309 [running]:
github.com/grafana/mimir/pkg/mimirpb.ReuseTimeseries(0xc000074500?)
	/Users/lhhdz/wd/projects/go/mimir/pkg/mimirpb/timeseries.go:438 +0x1e7
github.com/grafana/mimir/pkg/mimirpb.ReusePreallocTimeseries(0xc00732f958)
	/Users/lhhdz/wd/projects/go/mimir/pkg/mimirpb/timeseries.go:463 +0x27
github.com/grafana/mimir/pkg/mimirpb.ReuseSlice({0xc00732c000, 0x5b8, 0xa66})
	/Users/lhhdz/wd/projects/go/mimir/pkg/mimirpb/timeseries.go:421 +0x4a
github.com/grafana/mimir/pkg/api.(*API).RegisterDistributor.Handler.handler.func2.1.1()
	/Users/lhhdz/wd/projects/go/mimir/pkg/distributor/push.go:149 +0x2b
github.com/grafana/mimir/pkg/distributor.(*Request).CleanUp(0xc0201ace10)
	/Users/lhhdz/wd/projects/go/mimir/pkg/distributor/request.go:67 +0x2e
github.com/grafana/mimir/pkg/distributor.(*Distributor).push.func4()
	/Users/lhhdz/wd/projects/go/mimir/pkg/distributor/distributor.go:1333 +0x25
github.com/grafana/dskit/ring.DoBatchWithOptions.func2()
	/Users/lhhdz/wd/projects/go/mimir/vendor/github.com/grafana/dskit/ring/batch.go:173 +0x32
created by github.com/grafana/dskit/ring.DoBatchWithOptions.(*DoBatchOptions).replaceZeroValuesWithDefaults.func4 in goroutine 1690
	/Users/lhhdz/wd/projects/go/mimir/vendor/github.com/grafana/dskit/ring/batch.go:85 +0x13
```

## Cause
**The two go concoroutes execute pushReq.CleanUp() in different places respectively.**

execution point at routine 1 :
at `pkg/distributor/distributor.go:776`
```go
func (d *Distributor) prePushRelabelMiddleware(next PushFunc) PushFunc {
	return func(ctx context.Context, pushReq *Request) error {
		cleanupInDefer := true
		defer func() {
			if cleanupInDefer {
				pushReq.CleanUp()
			}
		}()
...
```

execution point at routine 2:
at `vendor/github.com/grafana/dskit/ring/batch.go:171`
```go
	// Perform cleanup at the end.
	o.Go(func() {
		wg.Wait()
		o.Cleanup()
	})

	select {
	case err := <-tracker.err:
		return err
	case <-tracker.done:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
```

**Comment by shichanglin5** [comment]
@pracucci

**Comment by shichanglin5** [comment]
You're right, I didn't notice that fix
