### ISSUE TITLE
Ingester segfault marshaling a LabelValuesResponse

### ISSUE THREAD

**Issue by seizethedave** [grafana/mimir#7897]
#### Describe the bug

We have several instances of this happening where ingesters segfault while attempting to marshal a `LabelValuesResponse`. It will often take out several ingesters. Sometimes these ingesters are in different zones of the same cluster, sometimes they're in the same zone.

#### To Reproduce
I don't have a reproduction at this time.

#### Environment

- Infrastructure: Kube

#### Additional Context

```
2024-04-09 06:51:51.771	unexpected fault address 0x7976968b824e
2024-04-09 06:51:51.771	fatal error: fault
2024-04-09 06:51:51.773	[signal SIGSEGV: segmentation violation code=0x1 addr=0x7976968b824e pc=0x472ea1]
2024-04-09 06:51:51.773	
2024-04-09 06:51:51.773	goroutine 3390042 [running]:
2024-04-09 06:51:51.773	runtime.throw({0x32cb84f?, 0xc083471538?})
2024-04-09 06:51:51.773		$GOROOT/src/runtime/panic.go:1077 +0x5c fp=0xc0834714c8 sp=0xc083471498 pc=0x43ba1c
2024-04-09 06:51:51.773	runtime.sigpanic()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/signal_unix.go:875 +0x285 fp=0xc083471528 sp=0xc0834714c8 pc=0x452a25
2024-04-09 06:51:51.773	runtime.memmove()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/memmove_amd64.s:184 +0x141 fp=0xc083471530 sp=0xc083471528 pc=0x472ea1
2024-04-09 06:51:51.773	github.com/grafana/mimir/pkg/ingester/client.(*LabelValuesResponse).MarshalToSizedBuffer(0xc0eb628078, {0xc137890000, 0x2d6a64, 0x2d6a64})
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/client/ingester.pb.go:5540 +0xdc fp=0xc083471570 sp=0xc083471530 pc=0x1cda43c
2024-04-09 06:51:51.773	github.com/grafana/mimir/pkg/ingester/client.(*LabelValuesResponse).Marshal(0xc0eb628078)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/client/ingester.pb.go:5520 +0x65 fp=0xc0834715b0 sp=0xc083471570 pc=0x1cda1c5
2024-04-09 06:51:51.773	google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x3a9f3c8, 0xc0eab27590}, {0x0, 0x0, 0x0}, 0x0})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:407 +0x9e fp=0xc083471630 sp=0xc0834715b0 pc=0x651ffe
2024-04-09 06:51:51.773	google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x8?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x3a9f3c8, 0xc0eab27590})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x25d fp=0xc0834716d0 sp=0xc083471630 pc=0x5e43dd
2024-04-09 06:51:51.773	google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x40?, 0x25?, 0x19?}, {0x0, 0x0, 0x0}, {0x3a4d480?, 0xc0eab27590?})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x73 fp=0xc083471718 sp=0xc0834716d0 pc=0x5e4033
2024-04-09 06:51:51.773	github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x79759e28b350?, 0xc0eb628078?}, 0x40?)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/golang/protobuf/proto/wire.go:40 +0x9e fp=0xc083471798 sp=0xc083471718 pc=0x9a38be
2024-04-09 06:51:51.773	github.com/golang/protobuf/proto.Marshal(...)
2024-04-09 06:51:51.773		/drone/src/vendor/github.com/golang/protobuf/proto/wire.go:23
2024-04-09 06:51:51.773	google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x3192540?, 0xc0eb628078})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/encoding/proto/proto.go:45 +0x4d fp=0xc0834717f0 sp=0xc083471798 pc=0xa4292d
2024-04-09 06:51:51.773	google.golang.org/grpc/encoding/proto.(*codec).Marshal(0x32cbcd7?, {0x3192540?, 0xc0eb628078?})
2024-04-09 06:51:51.773		<autogenerated>:1 +0x31 fp=0xc083471810 sp=0xc0834717f0 pc=0xa42b11
2024-04-09 06:51:51.773	google.golang.org/grpc.encode({0x7975a8355e90?, 0x540c3e0?}, {0x3192540?, 0xc0eb628078?})
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/rpc_util.go:633 +0x3e fp=0xc083471860 sp=0xc083471810 pc=0xaa2d9e
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).sendResponse(0xc000ff9a00, {0x3a6c760, 0xc04bf1ced0}, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0, {0x3192540?, 0xc0eb628078}, {0x0, 0x0}, ...)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1149 +0x9b fp=0xc083471970 sp=0xc083471860 pc=0xaa8a5b
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ff9a00, {0x3a6c760, 0xc04bf1ccf0}, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0, 0xc000d513e0, 0x53a7cb0, 0x0)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1432 +0xf4a fp=0xc083471d58 sp=0xc083471970 pc=0xaaa0ea
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).handleStream(0xc000ff9a00, {0x3a8f780, 0xc0c3caa9c0}, 0xc0671f50e0)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1796 +0xfec fp=0xc083471f30 sp=0xc083471d58 pc=0xaaf0ac
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serveStreams.func2.1()
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:1029 +0x8b fp=0xc083471f98 sp=0xc083471f30 pc=0xaa7eab
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serverWorker(0xc000ff9a00)
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:632 +0x25 fp=0xc083471fc8 sp=0xc083471f98 pc=0xaa49a5
2024-04-09 06:51:51.773	google.golang.org/grpc.(*Server).serverWorker.func1()
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:634 +0x25 fp=0xc083471fe0 sp=0xc083471fc8 pc=0xaa4a85
2024-04-09 06:51:51.773	runtime.goexit()
2024-04-09 06:51:51.773		$GOROOT/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc083471fe8 sp=0xc083471fe0 pc=0x471f61
2024-04-09 06:51:51.773	created by google.golang.org/grpc.(*Server).serverWorker in goroutine 2967518
2024-04-09 06:51:51.773		/drone/src/vendor/google.golang.org/grpc/server.go:634 +0xa6
```

**Comment by seizethedave** [comment]
My initial hunch is that the byte slice is large and stack-allocated, and may be overrunning the max stack size. (rlimit_stack.) This would generate a segmentation fault.

**Comment by seizethedave** [comment]
per the backtrace:
- the byte slice `{0xc137890000, 0x2d6a64, 0x2d6a64}` is heap allocated and is ~2.83 MiB.
- the sigsegv signal indicates
  - address= 0x7976968b824e: yes, this is definitely a wild memory address in the ~120 TiB neighborhood.
  - code=0x1: the address isn't in the mapped space for this process.
- is that giant address in the source or destination of the memmove call? seems more likely that it's the slice of source strings. Is there something fancy going on in there?
- Ah. The values are backed by the index file which is mmapped. The strings' byte slices are [pointing to ](https://github.com/grafana/mimir/blob/c35d88801c473cb1b2fca08c9220047def0ada58/vendor/github.com/prometheus/prometheus/tsdb/index/index.go#L1577)memory mapped regions. Note the comment in there: 
   ```
   // It is not safe to use the return value beyond the lifetime of the byte slice
   // passed into the Reader.
   ```
- There's nothing preventing the file from being unmapped while the gRPC/proto machinery marshals the string slice to the caller. This is probably the bug.

**Comment by aknuds1** [comment]
Which Mimir version is this?

**Comment by aknuds1** [comment]
@dimitarvdimitrov this might be of interest to you. I think we discussed whether the use of `yoloString` would be safe in [`index.Reader.LabelValues`](https://github.com/grafana/mimir/blob/c35d88801c473cb1b2fca08c9220047def0ada58/vendor/github.com/prometheus/prometheus/tsdb/index/index.go#L1577)?

**Comment by aknuds1** [comment]
We primarily need to know which Mimir or GEM version you are using, before we can investigate further.

**Comment by seizethedave** [comment]
Yeah, that is the bug. In one of the crashes, there's a goroutine running ingester's Compact() loop, which calls `deleteBlocks`, which closes compacted blocks, which had just called `munmap` before this process crashed.

```
2024-04-09 06:51:51.918	goroutine 3773562 [runnable]:
2024-04-09 06:51:51.918	syscall.Syscall6(0xc092f90ac0?, 0x11?, 0x470100?, 0x0?, 0x0?, 0x7975a8d5bbc8?, 0xa?)
2024-04-09 06:51:51.919		$GOROOT/src/syscall/syscall_linux.go:91 +0x30 fp=0xc0014dedd8 sp=0xc0014ded50 pc=0x4de230
2024-04-09 06:51:51.919	syscall.openat(0x797712069a38?, {0xc092f90ac0?, 0xc000098400?}, 0xc0953b4060?, 0x0)
2024-04-09 06:51:51.919		$GOROOT/src/syscall/zsyscall_linux_amd64.go:83 +0x8d fp=0xc0014dee50 sp=0xc0014dedd8 pc=0x4da9ad
2024-04-09 06:51:51.919	syscall.Open(...)
2024-04-09 06:51:51.919		$GOROOT/src/syscall/syscall_linux.go:272
2024-04-09 06:51:51.919	os.open({0xc092f90ac0?, 0x2f41bc0?}, 0xc0b8ce0001?, 0x14deef8?)
2024-04-09 06:51:51.919		$GOROOT/src/os/file_open_unix.go:15 +0x2b fp=0xc0014dee88 sp=0xc0014dee50 pc=0x507f0b
2024-04-09 06:51:51.919	os.openFileNolog({0xc092f90ac0, 0x11}, 0x0, 0x0)
2024-04-09 06:51:51.919		$GOROOT/src/os/file_unix.go:272 +0x8a fp=0xc0014deed0 sp=0xc0014dee88 pc=0x50938a
2024-04-09 06:51:51.919	os.OpenFile({0xc092f90ac0, 0x11}, 0x0, 0x5384ae0?)
2024-04-09 06:51:51.919		$GOROOT/src/os/file.go:334 +0x3e fp=0xc0014def08 sp=0xc0014deed0 pc=0x5074be
2024-04-09 06:51:51.919	os.Open(...)
2024-04-09 06:51:51.919		$GOROOT/src/os/file.go:314
2024-04-09 06:51:51.919	os.removeAll({0xc092f90ac0, 0x3d})
2024-04-09 06:51:51.919		$GOROOT/src/os/removeall_at.go:38 +0x19a fp=0xc0014defc0 sp=0xc0014def08 pc=0x50afda
2024-04-09 06:51:51.919	os.RemoveAll(...)
2024-04-09 06:51:51.919		$GOROOT/src/os/path.go:67
2024-04-09 06:51:51.919	github.com/prometheus/prometheus/tsdb.(*DB).deleteBlocks(0xc000933900, 0xc0014df448?)
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/prometheus/prometheus/tsdb/db.go:1752 +0x448 fp=0xc0014df188 sp=0xc0014defc0 pc=0x1acd828
2024-04-09 06:51:51.919	github.com/prometheus/prometheus/tsdb.(*DB).reloadBlocks(0xc000933900)
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/prometheus/prometheus/tsdb/db.go:1596 +0xaa5 fp=0xc0014dfb48 sp=0xc0014df188 pc=0x1acbea5
2024-04-09 06:51:51.919	github.com/prometheus/prometheus/tsdb.(*DB).compactOOOHead(0xc000933900, {0x3a6c568?, 0x540c3e0?})
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/prometheus/prometheus/tsdb/db.go:1321 +0xf3 fp=0xc0014dfc98 sp=0xc0014dfb48 pc=0x1ac9993
2024-04-09 06:51:51.919	github.com/prometheus/prometheus/tsdb.(*DB).Compact(0xc000933900, {0x3a6c568, 0x540c3e0})
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/prometheus/prometheus/tsdb/db.go:1277 +0x68d fp=0xc0014dfdf8 sp=0xc0014dfc98 pc=0x1ac904d
2024-04-09 06:51:51.919	github.com/grafana/mimir/pkg/ingester.(*userTSDB).Compact(...)
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/user_tsdb.go:181
2024-04-09 06:51:51.919	github.com/grafana/mimir/pkg/ingester.(*Ingester).compactBlocks.func1({0xc000e12a30?, 0xc001475001?}, {0xc00143117b, 0x6})
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/grafana/mimir/pkg/ingester/ingester.go:2919 +0x44a fp=0xc0014dfee8 sp=0xc0014dfdf8 pc=0x2211fea
2024-04-09 06:51:51.919	github.com/grafana/dskit/concurrency.ForEachUser.func1()
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/grafana/dskit/concurrency/runner.go:45 +0x132 fp=0xc0014dffe0 sp=0xc0014dfee8 pc=0x1856192
2024-04-09 06:51:51.919	runtime.goexit()
2024-04-09 06:51:51.919		$GOROOT/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0014dffe8 sp=0xc0014dffe0 pc=0x471f61
2024-04-09 06:51:51.919	created by github.com/grafana/dskit/concurrency.ForEachUser in goroutine 3814
2024-04-09 06:51:51.919		/drone/src/vendor/github.com/grafana/dskit/concurrency/runner.go:36 +0x126
```
general solutions:

1. offer variants of the methods in tsdb's `index.Reader` that return copied strings.
2. add the notion of a handle that callers can obtain from the index. This would also probably require us to write a custom gRPC-go codec, because we'd need to release the handle after `Marshal` is called. And there'd be the complexity of making ingester+tsdb block have a "closing" state where munmap doesn't happen until all handles are closed. (And new RPCs don't see "closing" blocks.)
3. others?

**Comment by seizethedave** [comment]
Thanks! I figured someone had crossed that bridge before.

I can imagine writing a custom gRPC `Codec` that becomes the _new_ "proto" codec, and then delegates to the _old_ built-in "proto", but also invokes a `Close` method if one exists. Something like:

```
func (m *MimirProtoCodec) Marshal(v any) ([]byte, error)
   defer func () {
      if c, ok := v.(Closer); ok {
         c.Close()
      }
   }
   return builtinProtoCodec.Marshal(v)
}

func (m *MimirProtoCodec) Unmarshal(data []byte, v any) error {
   return builtinProtoCodec.Unmarshal(data, v)
}
```

We'd need a place to stash a reference to the `Querier` that we'd be closing. Probably have to add an extra (serialization-ignored) field to the proto struct to track that.

Some things I find unsavory about this:
* we'd be taking the `defer querier.Close()` [bit](https://github.com/grafana/mimir/blob/2d363d053f1a3691f46734946474a17548a8f5e1/pkg/ingester/ingester.go#L1690) completely out of the request handler, and moving it to some magical "happens later" place. So, unit tests exercising the `LabelValues` handler would ... have to do some extra shenanigans to `Close` returned proto objects.
* I have read the gRPC server code - we are currently lucky in that after [invoking our RPC handler](https://github.com/grafana/mimir/blob/368edaebad68b716eb0d2e509072ae79cfff508a/vendor/google.golang.org/grpc/server.go#L1386) and before [marshaling the returned structs](https://github.com/grafana/mimir/blob/368edaebad68b716eb0d2e509072ae79cfff508a/vendor/google.golang.org/grpc/server.go#L1433) there are no early returns where we'd have to also inject `Close` calls. However, the grpc-go team could in the future add such early returns. (For example, no point continuing to marshal the struct if the context was closed...) It places us in an uneasy position of relying on the behavior of the grpc-go server internals where no contract exists. If such early returns were ever introduced, that would be a resource leak. (Stuck open block queriers -> blocks that can never close.)

Related (closed and locked 😄) issues from grpc-go:
* https://github.com/grpc/grpc-go/issues/5000 - as discussed in there, the `PreparedMsg` type is exactly the "I'll do my own marshaling and give you the bytes" power we need, but it's only implemented for streaming RPCs.
* https://github.com/grpc/grpc-go/issues/3906

Two other fledgling ideas I kind of like that would entail forking grpc-go:
* optional "lifecycle" hooks for proto messages. (`PreMarshal`, `Close`, etc.)
* implement `PreparedMsg` for unary RPCs

It is looking increasingly appetizing to just do one more copy of the labels slice and returning that in the proto struct. I'll do some analysis on the distribution of `LabelValues` payload sizes we typically see, and how often it is called. It might be kinda moot.

**Comment by aknuds1** [comment]
At least if you allocate a slice from the pool, for your copy, chances are it won't affect performance too much.

**Comment by seizethedave** [comment]
If we pooled it, we'd have to release it later after the marshal. (Correct me if I missed your point.)

**Comment by aknuds1** [comment]
You're right @seizethedave, I guess it would be equally tricky to release the slice to the pool again?
