### ISSUE TITLE
compactor: panic in r302

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#8908]
#### Describe the bug

```
panic: runtime error: index out of range [4] with length 4


goroutine 88061 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.insert[...]({0xc00aafe768?, 0xc00352a4c0?, 0x1b14725?}, {0xc0020ee4c0?, 0x0?, 0x4?}, {0xc0093945c0, 0x1, 0x1}, 0x0)
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram_meta.go:537 +0x158
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).recode(0xc000e83000?, {0xc0093945c0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0xc009394598, 0x1, 0x1}, ...)
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:728 +0x345
github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).AppendHistogram(0xc006f0e300, 0x0?, 0x1912220b803, 0xc006f13cc0, 0x0)
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:814 +0x115
github.com/prometheus/prometheus/storage.(*seriesToChunkEncoder).Iterator(0xc000e82f80?, {0x0, 0x0?})
	/drone/src/vendor/github.com/prometheus/prometheus/storage/series.go:344 +0x77d
github.com/prometheus/prometheus/storage.(*compactChunkIterator).Next(0xc000e038f0)
	/drone/src/vendor/github.com/prometheus/prometheus/storage/merge.go:821 +0x7d2
github.com/prometheus/prometheus/tsdb.DefaultBlockPopulator.PopulateBlock({}, {0x3ed9378, 0xc002b0c1e0}, 0xc002b281c0, {0x3eacb40, 0xc001e08410}, {0x3ec29c8, 0xc002b0ec80}, 0xc0023cb690, {0x4, ...}, ...)
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/compact.go:1161 +0x174f
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc002b2c750, {0xc00264a050, 0x4d}, {0xc000ae8460, 0x1, 0x1}, {0x3eb2b60, 0x5a98640}, {0xc002d4f900, 0x8, ...})
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/compact.go:875 +0xa5e
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).CompactWithBlockPopulator(0xc002b2c750, {0xc00264a050, 0x4d}, {0xc000c5c000, 0x8, 0x8}, {0x0, 0x0, 0x0}, {0x3eb2b60, ...}, ...)
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/compact.go:544 +0x7e9
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Compact(0xc00b006000?, {0xc00264a050?, 0xa?}, {0xc000c5c000?, 0xc000bfd000?, 0xc005159808?}, {0x0?, 0x7fa7fa4d5d78?, 0x3ee4150?})
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/compact.go:487 +0x4c
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).runCompactionJob(0xc0027caaa0, {0x3ed9378, 0xc000619540}, 0xc00104a1c0)
	/drone/src/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:365 +0x10b8
github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact.func2()
	/drone/src/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:857 +0x2ef
created by github.com/grafana/mimir/pkg/compactor.(*BucketCompactor).Compact in goroutine 110
	/drone/src/vendor/github.com/grafana/mimir/pkg/compactor/bucket_compactor.go:841 +0xbc7
```

#### To Reproduce

For now I can share a [zip file](https://drive.google.com/file/d/1BBDYNlOrIp_Z8Tg5ncX0abBeiTt1Io8u/view?usp=sharing) with a set of locks which cause the panic with GL employees.

**Comment by krajorama** [comment]
Testing fix https://github.com/prometheus/prometheus/pull/14598
